apiVersion: cloudresources.appvia.io/v2beta2
kind: CloudResourcePlan
metadata:
  name: aws-nodepool-build
spec:
  scope:
    allStages: true
    allWorkspaces: true
  cloud: aws
  description: nodepools for cluster provisioning on aws
  inputs:
  - description: The name to use for created cloud resources
    name: cloud_resource
    type: string
  - description: The name of the cluster to attach to
    name: cluster_name
    type: string
  - description: The version of kubernetes for created nodes
    name: kubernetes_version
    type: string
  - description: The default size of the nodepool
    name: size
    type: number
  - description: The minumum size of the nodepool
    name: min_size
    type: number
  - description: The maximum size of the nodepool
    name: max_size
    type: number
  - description: The instance_types to use in the nodepool
    name: instance_types
    type: list(string)
  - description: The private subnet ids in which nodes should be created
    name: private_subnet_ids
    type: list(string)
  terraform:
    moduleURL: https://github.com/appvia/terraform-aws-wayfinder-provisioning//nodepool/build
    moduleVersion: v0.0.1
    tfVarsTemplate: |
      cloud_resource = "{{ .Inputs.cloud_resource }}"
      cluster_name = "{{ .Inputs.cluster_name }}"
      kubernetes_version = "{{ .Inputs.kubernetes_version }}"
      size = {{ .Inputs.size }}
      min_size = {{ .Inputs.min_size }}
      max_size = {{ .Inputs.max_size }}
      instance_types = [{{ range $index, $element := .Inputs.instance_types }}{{if $index}},{{end}}"{{$element}}"{{end}}]
      subnet_ids = [{{ range $index, $element := .Inputs.private_subnet_ids }}{{if $index}},{{end}}"{{$element}}"{{end}}]
  version: 0.0.1
  permission: ClusterManager