apiVersion: policydelivery.appvia.io/v1alpha1
kind: GlobalAccessPolicy
metadata:
  name: editor.platdev
spec:
  accessPolicyTemplate:
    description: Editor access to platform-dev clusters
    accessRoleRefs:
    - cluster.view
    - namespace.edit
    - namespace.troubleshooting
    wayfinderGroups:
    - admin
    groups:
    - editor
    - member
    subjectType: User
    constraints:
      ttl: 8h00m0s
      clusters:
        allowed:
          matchLabels:
            "appvia.io/stage": "platdev"
