apiVersion: policydelivery.appvia.io/v1alpha1
kind: GlobalAccessPolicy
metadata:
  name: owner.prod
spec:
  accessPolicyTemplate:
    description: Allows workspace owners administrative access to production clusters in their workspace
    accessRoleRefs:
    - cluster.admin
    - namespace.admin
    wayfinderGroups:
    - admin
    groups:
    - owner
    subjectType: User
    constraints:
      ttl: 8h00m0s
      clusters:
        allowed:
          matchLabels:
            "appvia.io/stage": "prod"
