apiVersion: policydelivery.appvia.io/v1alpha1
kind: GlobalAccessPolicy
metadata:
  name: secretsviewer.platdev
spec:
  accessPolicyTemplate:
    description: Secrets read access to platform-dev clusters
    accessRoleRefs:
    - secrets.view
    groups:
    - secretsviewer-platdev
    subjectType: User
    constraints:
      ttl: 8h00m0s
      clusters:
        allowed:
          matchLabels:
            "appvia.io/stage": "platdev"
