apiVersion: policydelivery.appvia.io/v1alpha1
kind: GlobalAccessPolicy
metadata:
  name: viewer.platdev
spec:
  accessPolicyTemplate:
    description: View access to platform-dev clusters
    accessRoleRefs:
    - cluster.view
    - namespace.view
    groups:
    - viewer
    - member
    subjectType: User
    constraints:
      ttl: 8h00m0s
      clusters:
        allowed:
          matchLabels:
            "appvia.io/stage": "platdev"
