apiVersion: compute.appvia.io/v2beta2
kind: ComputeTemplate
metadata:
  name: eks-general-purpose-multitenant
spec:
  description: General purpose EKS node pool with quota limits for multi-tenant clusters
  provider: EKS

  nodePools:
  - logicalName: compute
    diskSize: 30
    image: AL2_x86_64
    machine: t3.large
    size: 2
    autoscaling:
      enabled: true
      maxSize: 10
      minSize: 2

  quotaLimits:
    default: small
    templates:
    - name: small
      constraints:
        hardQuota:
          "requests.cpu": "512m"
          "requests.memory": "1Gi"
        limitRanges:
        - type: Pod
          max:
            "cpu": "512m"
            "memory": "1024Mi"
            "ephemeral-storage": "4.5Gi"
      resourceDefaults:
      - type: Container
        default:
          "cpu": "512m"
          "memory": "1024Mi"
          "ephemeral-storage": "500Mi"
        defaultRequest:
          "cpu": "50m"
          "memory": "200m"
    - name: medium
      constraints:
        hardQuota:
          "requests.cpu": "1"
          "requests.memory": "2Gi"
        limitRanges:
        - type: Pod
          max:
            "cpu": "256m"
            "memory": "512Mi"
            "ephemeral-storage": "2.25Gi"
      resourceDefaults:
      - type: Container
        default:
          "cpu": "256m"
          "memory": "512Mi"
          "ephemeral-storage": "10Mi"
        defaultRequest:
          "cpu": "50m"
          "memory": "200m"
    - name: large
      constraints:
        hardQuota:
          "requests.cpu": "4Gi"
          "requests.memory": "8Gi"
        limitRanges:
        - type: Pod
          max:
            "cpu": "1"
            "memory": "2Gi"
            "ephemeral-storage": "9Gi"
      resourceDefaults:
      - type: Container
        default:
          "cpu": "1"
          "memory": "2Gi"
          "ephemeral-storage": "1Gi"
        defaultRequest:
          "cpu": "50m"
          "memory": "200Mi"

