apiVersion: compute.appvia.io/v2beta2
kind: ClusterPlan
metadata:
  name: aks-strict
spec:
  description: Hardened AKS cluster with a default "restricted" PSS Policy and no public ingress controller.
  version: "1.28.0"
  provider: AKS

  scope:
    allWorkspaces: true
    allStages: true

  cluster:
    kubernetesVersion: "1.28"
    packages:
    - name: ingress-nginx-internal
      version: "4.10.1-2"
    - name: cert-manager
      version: "1.14.5-1"
    - name: external-dns-azure-private
      version: "7.2.1-2"
    - name: kyverno
      version: "2.7.3-5"
    - name: terranetes-controller
      version: "0.7.12-1"

    providerDetails:
      aks:
        skuTier: Standard
        nodeOSUpgradeChannel: NodeImage

    security:
      podSecurityStandard:
        enabled: true
        defaultProfile: restricted
        allowed: ["restricted"]

  network:
    networkPlan: aks-standard
    authorizedMasterNetworks:
    - cidr: 0.0.0.0/0
      name: default
    authorizedNetworks:
    - cidr: 0.0.0.0/0
      name: default
    aksServicesNetwork: 172.16.0.0/16