apiVersion: compute.appvia.io/v2beta2
kind: ClusterPlan
metadata:
  name: aks-strict
  annotations:
    appvia.io/published: "true"
spec:
  description: Hardened AKS cluster with a restricted PSS Policy and no public ingress controller
  version: "1.1.1"
  provider: AKS

  scope:
    allWorkspaces: true
    allStages: true

  cluster:
    kubernetesVersion: "1.30"
    packages:
    - name: ingress-nginx-internal
      version: "4.11.3-1"
    - name: cert-manager
      version: "1.15.3-2"
    - name: external-dns-azure-private
      version: "8.3.9-1"
    - name: kyverno
      version: "2.7.3-6"
    - name: terranetes-controller
      version: "0.7.21-1"

    providerDetails:
      aks:
        skuTier: Standard
        nodeOSUpgradeChannel: NodeImage

    security:
      podSecurityStandard:
        enabled: true
        defaultProfile: restricted
        allowed: ["restricted"]

  network:
    networkPlan: aks-standard
    authorizedMasterNetworks:
    - cidr: 0.0.0.0/0
      name: default
    authorizedNetworks:
    - cidr: 0.0.0.0/0
      name: default
    aksServicesNetwork: 172.16.0.0/16