apiVersion: compute.appvia.io/v2beta2
kind: ClusterPlan
metadata:
  name: eks-general-purpose
spec:
  description: General purpose EKS cluster.
  version: "1.29.0"
  provider: EKS

  scope:
    allWorkspaces: true
    allStages: true

  cluster:
    kubernetesVersion: "1.29"
    packages:
    - name: aws-ebs-csi-snapshot-controller
      version: "2.2.2-1"
    - name: aws-ebs-csi-driver
      version: "2.30.0-1"
    - name: tigera-operator
      version: "3.27.3-1"
    - name: metrics-server
      version: "3.12.1-1"
    - name: cluster-autoscaler
      version: "9.36.0-1"
    - name: ingress-nginx
      version: "4.10.1-1"
    - name: cert-manager
      version: "1.14.5-1"
    - name: external-dns
      version: "7.2.1-2"
    - name: kyverno
      version: "2.7.3-5"
    - name: terranetes-controller
      version: "0.7.12-1"

    providerDetails:
      eks:
        cloudWatchLogging:
          audit: true

    security:
      podSecurityStandard:
        enabled: true
        defaultProfile: baseline
        allowed: ["restricted", "baseline", "privileged"]

  network:
    networkPlan: eks-standard
    authorizedMasterNetworks:
      - cidr: 0.0.0.0/0
        name: default
    authorizedNetworks:
      - cidr: 0.0.0.0/0
        name: default
