apiVersion: compute.appvia.io/v2beta2
kind: ClusterPlan
metadata:
  name: eks-general-purpose
  annotations:
    appvia.io/published: "true"
spec:
  description: General purpose EKS cluster
  version: "1.1.0"
  provider: EKS

  scope:
    allWorkspaces: true
    allStages: true

  cluster:
    kubernetesVersion: "1.30"
    packages:
    - name: aws-ebs-csi-snapshot-controller
      version: "3.0.6-1"
    - name: aws-ebs-csi-driver
      version: "2.35.1-1"
    - name: tigera-operator
      version: "3.28.2-0"
    - name: metrics-server
      version: "3.12.1-1"
    - name: cluster-autoscaler
      version: "9.37.0-1"
    - name: ingress-nginx
      version: "4.11.2-1"
    - name: cert-manager
      version: "1.15.3-1"
    - name: external-dns
      version: "8.3.8-1"
    - name: kyverno
      version: "2.7.3-5"
    - name: terranetes-controller
      version: "0.7.20-2"

    providerDetails:
      eks:
        cloudWatchLogging:
          audit: true

    security:
      podSecurityStandard:
        enabled: true
        defaultProfile: baseline
        allowed: ["restricted", "baseline", "privileged"]

  network:
    networkPlan: eks-standard
    authorizedMasterNetworks:
      - cidr: 0.0.0.0/0
        name: default
    authorizedNetworks:
      - cidr: 0.0.0.0/0
        name: default
