apiVersion: compute.appvia.io/v2beta2
kind: ClusterPlan
metadata:
  name: eks-strict
  annotations:
    appvia.io/published: "true"
spec:
  description: Hardened EKS cluster with a restricted PSS Policy and no public ingress controller
  version: "1.3.0"
  provider: EKS

  scope:
    allWorkspaces: true
    allStages: true

  cluster: 
    kubernetesVersion: "1.32"
    packages:
    - name: aws-ebs-csi-snapshot-controller
      version: "3.0.6-2"
    - name: aws-ebs-csi-driver
      version: "2.35.1-2"
    - name: aws-load-balancer-controller
      version: "1.9.0-1"
    - name: tigera-operator
      version: "3.28.2-1"
    - name: metrics-server
      version: "3.12.1-2"
    - name: cluster-autoscaler
      version: "9.43.0-1"
    - name: ingress-nginx-internal
      version: "4.11.3-1"
    - name: cert-manager
      version: "1.15.3-2"
    - name: external-dns
      version: "10.19.0-1"
    - name: kyverno
      version: "2.7.3-6"
    - name: terranetes-controller
      version: "0.7.21-1"

    providerDetails:
      eks:
        cloudWatchLogging:
          api: true
          audit: true
          authenticator: true
          controllerManager: true
          scheduler: true
        encryption:
          secretsEncryptionEnabled: true
        generateLaunchTemplate: true
        imdsV2Required: true
        # Required for, at least, the AWS load balancer controller:
        # https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.10/deploy/installation/#using-the-amazon-ec2-instance-metadata-server-version-2-imdsv2
        imdsTokenResponseHopLimit: 2
    security:
      podSecurityStandard:
        enabled: true
        defaultProfile: restricted
        allowed: ["restricted"]

  network:
    networkPlan: eks-standard
    authorizedMasterNetworks:
      - cidr: 0.0.0.0/0
        name: default
    authorizedNetworks:
      - cidr: 0.0.0.0/0
        name: default