apiVersion: compute.appvia.io/v2beta2
kind: ClusterPlan
metadata:
  name: gke-general-purpose
spec:
  description: General purpose GKE cluster.
  version: "1.29.0"
  provider: GKE

  scope:
    allWorkspaces: true
    allStages: true

  cluster:
    kubernetesVersion: "1.29"
    packages:
    - name: ingress-nginx
      version: "4.10.1-1"
    - name: cert-manager
      version: "1.14.5-1"
    - name: external-dns
      version: "7.2.1-2"
    - name: kyverno
      version: "2.7.3-5"

    providerDetails:
      gke:
        enableHTTPLoadBalancer: false
        enableHorizontalPodAutoscaler: true
        enableShieldedNodes: false
        enableStackDriverLogging: true
        enableStackDriverMetrics: true
        masterIPV4Cidr: 172.16.0.16/28

    security:
      podSecurityStandard:
        enabled: true
        defaultProfile: baseline
        allowed: ["restricted", "baseline", "privileged"]

  network:
    networkPlan: gke-standard
    authorizedMasterNetworks:
      - cidr: 0.0.0.0/0
        name: default
    authorizedNetworks:
      - cidr: 0.0.0.0/0
        name: default
