apiVersion: compute.appvia.io/v2beta2
kind: ClusterPlan
metadata:
  name: gke-sandbox
  annotations:
    appvia.io/published: "true"
spec:
  description: Low cost cluster configuration for testing purposes
  version: "1.1.0"
  provider: GKE

  scope:
    allWorkspaces: true
    allStages: true

  cluster:
    kubernetesVersion: "1.30"
    packages:
    - name: ingress-nginx
      version: "4.11.2-1"
    - name: cert-manager
      version: "1.15.3-1"
    - name: external-dns
      version: "8.3.8-1"
    - name: kyverno
      version: "2.7.3-5"

    providerDetails:
      gke:
        enableHTTPLoadBalancer: false
        enableHorizontalPodAutoscaler: true
        enableShieldedNodes: false
        enableStackDriverLogging: false
        enableStackDriverMetrics: false
        masterIPV4Cidr: 172.16.0.16/28

    security:
      podSecurityStandard:
        enabled: true
        defaultProfile: baseline
        allowed: ["restricted", "baseline", "privileged"]

  network:
    networkPlan: gke-standard
    authorizedMasterNetworks:
      - cidr: 0.0.0.0/0
        name: default
    authorizedNetworks:
      - cidr: 0.0.0.0/0
        name: default