apiVersion: compute.appvia.io/v2beta2
kind: ClusterPlan
metadata:
  name: gke-strict
  annotations:
    appvia.io/published: "true"
spec:
  description: Hardened GKE cluster with a restricted PSS Policy and no public ingress controller
  version: "1.1.2"
  provider: GKE

  scope:
    allWorkspaces: true
    allStages: true

  cluster: 
    kubernetesVersion: "1.31"
    packages:
    - name: ingress-nginx-internal
      version: "4.11.3-1"
    - name: cert-manager
      version: "1.15.3-2"
    - name: external-dns
      version: "8.3.9-1"
    - name: kyverno
      version: "2.7.3-6"
    - name: cluster-rbac
      version: "1.0.0"

    providerDetails:
      gke:
        enableHTTPLoadBalancer: false
        enableHorizontalPodAutoscaler: true
        enableShieldedNodes: true
        enableStackDriverLogging: true
        enableStackDriverMetrics: true
        masterIPV4Cidr: 172.16.0.16/28

    security:
      appDeploymentRoleDefault: wf.deployment.default
      appDeploymentRoleLabels:
        appvia.io/appdeployment: "true"
      podSecurityStandard:
        enabled: true
        defaultProfile: restricted
        allowed: ["restricted"]

  network:
    networkPlan: gke-standard
    authorizedMasterNetworks:
      - cidr: 0.0.0.0/0
        name: default
    authorizedNetworks:
      - cidr: 0.0.0.0/0
        name: default