apiVersion: networking.appvia.io/v2beta1
kind: ClusterNetworkPlan
metadata:
  name: eks-standard
spec:
  summary: General purpose EKS cluster network.

  template:
    plan: eks-standard
    provider: aws
    providerDetails:
      type: aws
      aws:
        availabilityZones: 3
        natGateways: 3
    ipv4:
      cidrBlocks:
      - type: node
        cidr: 10.0.0.0/24
    layout:
      mode: auto
      privateSubnets: 3
      publicSubnets: 3
