---
apiVersion: package.appvia.io/v2beta2
kind: Package
metadata:
  name: aws-ebs-csi-snapshot-controller
  annotations:
    appvia.io/displayName: "EBS CSI Snapshot Controller (AWS)"
    appvia.io/packageProviderFilter: "EKS"
spec:
  description: Provides snapshot support to EKS clusters using AWS EBS
  version: "3.0.6-2"
  installNamespace: snapshot-controller

  helm:
    releaseName: snapshot-controller
    repositoryRef: piraeus-charts
    chartName: snapshot-controller
    chartVersion: "3.0.6"
