---
apiVersion: package.appvia.io/v2beta2
kind: Package
metadata:
  name: external-dns-azure-private
  annotations:
    appvia.io/displayName: "External DNS for Azure (Private)"
spec:
  version: "10.19.0-1"
  installNamespace: external-dns-private
  description: External DNS for Azure allows Kubernetes to manage DNS zones on Azure Private DNS

  helm:
    releaseName: external-dns-azure-private
    helmTimeout: 300s
    repositoryRef: external-dns
    chartName: external-dns
    chartVersion: "1.19.0"
    valuesTemplate: |
      domainFilters:
      {{- range .Cluster.DNSZones }}
      {{- if .Private }}
      - {{ .Domain }}
      {{- end }}
      {{- end }}
      fullnameOverride: external-dns-private
      logFormat: json
      policy: sync
      txtOwnerId: {{ .Cluster.Name }}
      serviceMonitor:
        enabled: false
      resources:
        limits:
          memory: 50Mi
        requests:
          cpu: 10m
          memory: 50Mi
      serviceAccount:
        create: true
        name: {{ .Package.WorkloadIdentity.ServiceAccountName }}
        annotations:
      {{ .Package.WorkloadIdentity.ServiceAccountAnnotations | toYaml | indent 4 }}
      podLabels:
      {{ .Package.WorkloadIdentity.PodLabels | toYaml | indent 2 }}
      {{- $resGrp := "" }}
      {{- range .Cluster.DNSZones }}
        {{- if .Private }}
          {{- $resGrp = .Azure.ResourceGroup }}
        {{- end }}
      {{- end }}
      {{- if $resGrp }}
      provider:
        name: azure-private-dns
      extraArgs:
      - --azure-resource-group={{ $resGrp }}
      secretConfiguration:
        enabled: true
        mountPath: /etc/kubernetes
        data:
          azure.json: |
            {
              "tenantId": "{{ .CloudAccessConfig.Azure.Tenant }}",
              "subscriptionId": "{{ .CloudAccessConfig.Azure.Subscription }}",
              "resourceGroup": "{{ $resGrp }}",
              "useWorkloadIdentityExtension": true
            }
      {{- end }}

  workloadIdentity:
    serviceAccountName: external-dns
    role:
      azure:
        roleAssignmentsTemplate: |
          # must always have a valid role for the workload identity to work
          - scope: /subscriptions/{{ .CloudAccessConfig.Azure.Subscription }}
            roleDefinitionName: Reader
          {{- $resGrp := "" }}
          {{- if .Cluster.DNSZones }}
            {{- range .Cluster.DNSZones }}
              {{- if .Private }}
              {{- $resGrp = .Azure.ResourceGroup }}
          - scope: {{ .ZoneID }}
            roleDefinitionName: Contributor
              {{- end }}
            {{- end }}
          {{- end }}
          {{- if $resGrp }}
          - scope: /subscriptions/{{ .CloudAccessConfig.Azure.Subscription }}/resourceGroups/{{ $resGrp }}
            roleDefinitionName: Reader
          {{- end }}
