---
apiVersion: package.appvia.io/v2beta2
kind: Package
metadata:
  name: external-dns
  annotations:
    appvia.io/displayName: "External DNS"
spec:
  description: External DNS allows Kubernetes to manage DNS zones
  version: "8.3.9-1"
  installNamespace: external-dns

  helm:
    releaseName: external-dns
    helmTimeout: 300s
    repositoryRef: bitnami
    chartName: external-dns
    chartVersion: "8.3.9"
    valuesTemplate: |
      domainFilters:
      {{- range .Cluster.DNSZones }}
      - {{ .Domain }}
      {{- end }}
      fullnameOverride: external-dns
      logFormat: json
      policy: sync
      txtOwnerId: {{ .Cluster.Name }}
      replicas: 2
      crd:
        create: false
      metrics:
        enabled: true
        serviceMonitor:
          enabled: false
      rbac:
        apiVersion: v1
      resources:
        limits:
          memory: 50Mi
        requests:
          cpu: 10m
          memory: 50Mi
      serviceAccount:
        create: true
        name: {{ .Package.WorkloadIdentity.ServiceAccountName }}
        annotations:
      {{ .Package.WorkloadIdentity.ServiceAccountAnnotations | toYaml | indent 4 }}
      podLabels:
      {{ .Package.WorkloadIdentity.PodLabels | toYaml | indent 2 }}

      {{- if .Cluster.AWS }}
      provider: aws
      aws:
        region: {{ .Cluster.Region }}
      {{- end }}
      {{- if .Cluster.Azure }}
      {{- $resGrp := "" }}
      {{- range .Cluster.DNSZones }}
        {{- if not .Private }}
          {{- $resGrp = .Azure.ResourceGroup }}
        {{- end }}
      {{- end }}
      {{- if $resGrp }}
      provider: azure
      azure:
        tenantId: {{ .CloudAccessConfig.Azure.Tenant }}
        subscriptionId: {{ .CloudAccessConfig.Azure.Subscription }}
        useWorkloadIdentityExtension: true
        resourceGroup: {{ $resGrp }}
      {{- end }}
      {{- end }}
      {{- if .Cluster.GCP }}
      provider: google
      {{- end }}

  workloadIdentity:
    serviceAccountName: external-dns
    role:
      aws:
        customIAMPolicyTemplate: |
          Version: "2012-10-17"
          Statement:
          {{- if .Cluster.DNSZones }}
          - Sid: "AllowRoute53ChangeResourceRecordSets"
            Effect: "Allow"
            Action:
            - "route53:ChangeResourceRecordSets"
            Resource:
            {{- range .Cluster.DNSZones }}
            {{- if .AWS }}
            - "arn:aws:route53:::{{ trimPrefix "/" .ZoneID }}"
            {{- end }}
            {{- end }}
          {{- end }}
          # must always have a valid role for the workload identity to work
          - Sid: "AllowRoute53List"
            Effect: "Allow"
            Action:
            - "route53:GetChange"
            - "route53:ListHostedZones"
            - "route53:ListResourceRecordSets"
            - "route53:ListHostedZonesByName"
            Resource:
            - "*"

      azure:
        roleAssignmentsTemplate: |
          # must always have a valid role for the workload identity to work
          - scope: /subscriptions/{{ .CloudAccessConfig.Azure.Subscription }}
            roleDefinitionName: Reader
          {{- if .Cluster.DNSZones }}
            {{- range .Cluster.DNSZones }}
              {{- if not .Private }}
          - scope: {{ .ZoneID }}
            roleDefinitionName: Contributor
              {{- end }}
            {{- end }}
          {{- end }}

      gcp:
        iamRoleBindingsTemplate: |
          # must always have a valid role for the workload identity to work
          - role: roles/dns.reader
            scopeType: Project
          {{- if .Cluster.DNSZones }}
            {{- range .Cluster.DNSZones }}
              {{- if .GCP }}
          - role: roles/dns.admin
            scopeType: Project
              {{- end }}
            {{- end }}
          {{- end }}
