---
apiVersion: package.appvia.io/v2beta2
kind: Package
metadata:
  name: ingress-nginx-cert
  annotations:
    appvia.io/displayName: "External Ingress Nginx with default TLS certificate"
spec:
  version: "4.11.3-2"
  installNamespace: ingress
  description: Enables the capability to provision ingress services with a valid TLS certificate for the cluster's dynamic DNS zone.
  dependencies:
    - cert-manager
  manifests:
    - name: default-cert.yaml
      preInstall: true
      template: |
        {{- if .Cluster.PublicDNSDomain }}
        apiVersion: cert-manager.io/v1
        kind: Certificate
        metadata:
          name: cluster-wildcard-cert
        spec:
          dnsNames:
          - "*.{{ .Cluster.Name }}.{{ .Cluster.PublicDNSDomain }}"
          - "*.{{ .Cluster.PublicDNSDomain }}"
          issuerRef:
            kind: ClusterIssuer
            name: le-prod
          secretName: cluster-wildcard-cert
          usages:
          - digital signature
          - key encipherment
        {{- end }}
  helm:
    releaseName: ingress-nginx
    chartName: ingress-nginx
    repositoryRef: ingress-nginx
    chartVersion: "4.11.3"
    # time for a load balancer to be created
    helmTimeout: 300s

    valuesTemplate: |
      controller:
        {{- if .Cluster.PublicDNSDomain }}
        extraArgs:
          default-ssl-certificate: "ingress/cluster-wildcard-cert"
        {{- end }}
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                    - ingress
                topologyKey: failure-domain.beta.kubernetes.io/zone
              weight: 100
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                    - ingress
                topologyKey: kubernetes.io/hostname
              weight: 95
        allowSnippetAnnotations: false
        autoscaling:
          enabled: false
          maxReplicas: 6
          minReplicas: 2
          targetCPUUtilizationPercentage: 75
          targetMemoryUtilizationPercentage: 70
        {{- if .Cluster.AWS }}
        config:
          use-proxy-protocol: "true"
        {{- end }}
        ingressClass: external
        ingressClassResource:
          controllerValue: k8s.io/ingress-nginx
          default: true
          enabled: true
          name: external
        metrics:
          enabled: true
        networkPolicy:
          enabled: true
        replicaCount: 2
        resources:
          limits:
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 100Mi
        service:
          {{- if .Cluster.AWS }}
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
            service.beta.kubernetes.io/aws-load-balancer-type: "external"
            service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"
            service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
          {{- else }}
          externalTrafficPolicy: Local
          {{- end }}
        updateStrategy:
          rollingUpdate:
            maxUnavailable: 1
          type: RollingUpdate
        admissionWebhooks:
          enabled: true
          networkPolicyEnabled: true
      fullnameOverride: ingress
      priorityClassName: system-cluster-critical
      podSecurityPolicy:
        enabled: false
