---
apiVersion: package.appvia.io/v2beta2
kind: Package
metadata:
  name: ingress-nginx-internal
  annotations:
    appvia.io/createdBy: "Wayfinder"
    appvia.io/displayName: "Internal Ingress Nginx"
spec:
  version: "4.11.3-1"
  installNamespace: ingress-internal
  description: Enables the capability to provision internal ingress services

  helm:
    releaseName: ingress-nginx-internal
    chartName: ingress-nginx
    repositoryRef: ingress-nginx
    chartVersion: "4.11.3"
    # time for a load balancer to be created
    helmTimeout: 300s

    valuesTemplate: |
      controller:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                    - ingress
                topologyKey: failure-domain.beta.kubernetes.io/zone
              weight: 100
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                    - ingress
                topologyKey: kubernetes.io/hostname
              weight: 95
        allowSnippetAnnotations: false
        autoscaling:
          enabled: false
          maxReplicas: 6
          minReplicas: 2
          targetCPUUtilizationPercentage: 75
          targetMemoryUtilizationPercentage: 70
        {{- if .Cluster.AWS }}
        config:
          use-proxy-protocol: "true"
        {{- end }}
        ingressClass: internal
        ingressClassResource:
          controllerValue: k8s.io/ingress-nginx-internal
          default: false
          enabled: true
          name: internal
        metrics:
          enabled: true
        networkPolicy:
          enabled: true
        replicaCount: 2
        resources:
          limits:
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 100Mi
        service:
          annotations:
            {{- if .Cluster.AWS }}
            service.beta.kubernetes.io/aws-load-balancer-scheme: "internal"
            service.beta.kubernetes.io/aws-load-balancer-type: "external"
            service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"
            service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
            {{- else if .Cluster.Azure }}
            service.beta.kubernetes.io/azure-load-balancer-internal: "true"
            {{- else if .Cluster.GCP }}
            networking.gke.io/load-balancer-type: "Internal"
            {{- end }}
          {{- if not .Cluster.AWS }}
          externalTrafficPolicy: Local
          {{- end }}
        updateStrategy:
          rollingUpdate:
            maxUnavailable: 1
          type: RollingUpdate
        admissionWebhooks:
          enabled: true
          networkPolicyEnabled: true
      fullnameOverride: ingress-internal
      priorityClassName: system-cluster-critical
      podSecurityPolicy:
        enabled: false
