---
apiVersion: package.appvia.io/v2beta2
kind: Package
metadata:
  name: kyverno
  annotations:
    appvia.io/displayName: "Kyverno Policy"
spec:
  version: "2.7.3-8"
  installNamespace: kyverno
  description: kyverno in clusters

  helm:
    releaseName: kyverno
    chartName: kyverno
    repositoryRef: wayfinder-builtin
    chartVersion: "2.7.3"
    helmTimeout: 300s

    valuesTemplate: |
      priorityClassName: wf-system-critical
      config:
        webhooks:
        - namespaceSelector:
            matchExpressions:
            - key: kubernetes.io/metadata.name
              operator: NotIn
              values:
              - kube-system
      resources:
        # Use a higher memory limit than the default as if this is OOMKilled the
        # cluster can be unusable.
        limits:
          memory: 1024Mi
      # Run in high-availability mode as documented here: https://kyverno.io/docs/installation/methods/#high-availability-installation
      admissionController:
        replicas: 3
      backgroundController:
        replicas: 2
      cleanupController:
        replicas: 2
      reportsController:
        replicas: 2