apiVersion: package.appvia.io/v2beta2
kind: Package
metadata:
  name: tigera-operator
  annotations:
    appvia.io/createdBy: "Wayfinder"
    appvia.io/displayName: "Tigera operator"
spec:
  version: "3.27.3-1"
  installNamespace: kube-system
  description: Enables the ability to create policies around network traffic

  helm:
    releaseName: tigera-operator
    chartName: tigera-operator
    repositoryRef: wayfinder-builtin
    chartVersion: "v3.27.3"
    valuesTemplate: |
      installation:
        kubernetesProvider: EKS
